apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: learning-agent
data:
  01-enable-pgvector.sql: |
    -- Enable pgvector extension
    CREATE EXTENSION IF NOT EXISTS vector;
