#!/usr/bin/env sh
set -e

echo "Running lint-staged..."
npx lint-staged

echo "Running backend tests..."
npm --prefix backend test -- --passWithNoTests

#echo "Building frontend..."
#if npm --prefix client run build; then
#  echo "Frontend build completed successfully"
#else
#  echo "Frontend build failed, but commit will continue"
#fi

echo "Building backend..."
if npm --prefix backend run build; then
  echo "Backend build completed successfully"
else
  echo "Backend build failed, but commit will continue"
fi